from django.conf import settings

MERCHANT = settings.ZARINPAL['MERCHANT']
DESCRIPTION = settings.ZARINPAL['DESCRIPTION']
CALLBACK = settings.ZARINPAL['CALLBACK']
REDIRECT_URL = settings.ZARINPAL['REDIRECT_URL']
REDIS_DB = settings.ZARINPAL['REDIS_DB']
